---
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    template: ./resources/aog-latex-ms.tex
  word_document:
    reference_docx: ./resources/aog_word_style.docx
fontfamily: mathpazo
fontsize: 11pt
anonymous: false
endnotes: false
pagenumber: 1
bibliography: ../project.bib
biblio-style: ./resources/ajs.bst
title: "Archaeobotanical Analysis of Huizui Seeds"
author:
- affiliation: University of Oregon, Anthropology
  name: Yuan Fang
- affiliation: Some Research University
  name: My co-author
keywords: keywords
thanks: Thanks to people and stuff
abstract: This is a test abstract
---

# Introduction

The Huizui site is located in the Yiluo valley in Yanshi County, western Henan Province, China (Ford 2004, 71; Lee and Bestel 2007, 49). It has been considered a stone tool production locus during the late Longshan and Erlitou times (c. 2,500 – 1,600 BC) and a secondary center in the hinterland of the Erlitou state (Ford 2004; Liu et al. 2013, 278-279). The Yiluo archaeological team has conducted intensive excavations at the Huizui site since 1998, revealing a total of 665 square meters of human occupation of the site (Lee and Bestel 2007, 49). Previous archaeobotanical studies on Erlitou period Huizui site have confirmed a dominant dryland farming subsistence in this region. At least eighteen archaeobotanical taxa were identified, with foxtail millet as the most common single crop, followed by broomcorn millet (51). However, very few statistical analyses have been done to examine possible contextual factors contributing to the development of dryland farming in this area. This paper will conduct a statistical analysis on charred seeds from the Huizui site. It aims to study the relationship between certain seed densities (soybeans, foxtail millets, etc.) and some contextual factors such as archaeological feature types (ash pits, ditches, houses, etc.), time periods (Erlitou, Longshan, etc.), proportions of other seeds among total soil samples, etc. This analysis will help us better understand the farming patterns and possible drivers of dryland farming in the Huizui area. 


# Data and Methods

The Huizui site today is separated by a modern gully, and the two separated areas of the site are referred to as Huizui East (10 ha) and Huizui West (4 ha), the latter only being occupied during the Erlitou period (Lee and Bestel 2007, 49; Liu et al. 2013, 291). The Yiluo archaeological team gathered soil samples from the Huizui site from 2000 to 2006 for archaeobotanical analysis. The samples were collected from different excavation grids covering the whole site. The University of Oregon Archaeobotany Lab at the Anthropology Department has been conducting the analyzing work. At the lab, the soil samples were processed by flotation and only the light fractions were kept. The light portions then went through a sieving process to be further classified into 2mm, 1mm, 0.4mm and 0.2mm groups. The samples were then ready to be examined and seeds identified under a Nikon microscope. Every sample was recorded with sample number, feature (the trench and unit #), feature type (ditch/house/ash pits, etc.), historical period, total weight, charcoal weight, volume, number of seeds found for each taxa, and the percentage of work done for different sieving groups. There is a total of 126 samples from the Huizui site available to be used in the following analysis.


# Results

# Conclusions

# References

Ford, Anne. 2004. “Ground Stone Tool Production at Huizui, China: An Analysis of A Manufacturing Site in the Yilou River Basin.” Bulletin of the Indo-Pacific Prehistory Association 24: 71–78.

Lee, Gyoung-Ah, and Sheahan Bestel. 2007. “Contextual Analysis of Plant Remains at the Erlitou-Period Huizui Site, Henan, China.” Bulletin of the Indo-Pacific Prehistory Association 27: 49–60.

Liu, Li, Shaodong Zhai, and Xingcan Chen. 2013. “Production of Ground Stone Tools at Taosi and Huizui: A Comparison.” In A Companion to Chinese Archaeology Pp. 278–299. Hoboken, NJ: John Wiley & Sons Inc.